### ISSUE TITLE
How to rename query fields when forwarding

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-binding#48]
Let's say I want to forward the `allPosts` field to the `posts` field using `forwardTo`, is that possible?

A next step would be to also forward the `filter` input argument to the `where` input argument.

**Comment by kbrandwijk** [comment]
No, if that's what you need, use the binding in your resolver. `forwardTo` is really a convenience method for forwarding to the same root field with the same arguments. In your case, use:
```
const resolvers = {
  Query: {
    allPosts: (parent, { filter }, context, info) => {
      return context.db.query.posts({ where: filter }, info)
    } 
  }
}
```

**Comment by marktani** [comment]
Thanks! 🙂

**Comment by Pkmmte** [comment]
How would this work with mutations?

I'm migrating from Graphcool to Prisma and am concerned about having to update mutations this way because they'd essentially be calling themselves. Wouldn't this end in an infinite loop? Any easy way to, for example, make `updateUser(*stuff*)` call `updateUser(data: *stuff*)`?

**Comment by kbrandwijk** [comment]
@Pkmmte This wouldn't cause a loop, because you'll be calling `updateUser(data: ...)` on the binding explicitly.
